In [1]:
import requests
import numpy as np
from bs4 import BeautifulSoup
import pandas as pd
import lxml.html as lxl
import re

In [2]:
response = requests.get("https://www.propertypro.ng/property-for-rent?page=")

In [3]:
data = response.text

In [4]:
soup = BeautifulSoup(data, "html.parser")

In [5]:
listings = soup.find_all(class_ = "listings-property-title2")

In [6]:
description = [listing.text for listing in listings]

In [7]:
description

['Recently Renovated City View 4 Bedroom Apartment + Bq + Gym + Tennis Court + Squash + Pool+gym Etc In Ocean Parade Banana Island',
 'Serviced 4 Bedroom Semi Detached Duplex With Excellent Facilities',
 'Luxury 12 Units Of 3 Bedroom Apartments In A Gated Estate',
 'Luxury 4 Bedroom Apartment +bq',
 'Furnished 3 Bedroom Apartment + Bq',
 '4 Bedroom Apartments + Bq+gym+tennis Court',
 'New & Premium 4 Bedroom Apartment',
 'Premium 3 Bedroom Apartment + Bq+elevator',
 'Newly Renovated 3 Bedroom Flat',
 'Newly Renovated 3 Bedroom Flat',
 'Newly Built 4 Bedroom Semi Detached Duplex',
 'Newly Built Mini Flat',
 'A Big 2 Bedroom Apartment',
 '4 Bedroom Detached Duplex',
 '4 Bedroom Terrace Duplex',
 '4 Bedroom Terrace',
 'Partly Furnished 5 Bedroom Detached Duplex',
 '4 Bedroom Terrace',
 'Premium 4 Bedroom Semi Detached Terrace House + Bq+pool+gym Etc',
 'Brand New Fully Furnished 3bedroom Apartment',
 'Tastefully Built 4 Bedroom Semi Detached Duplex;',
 'Elegant 4 Bedroom Terrace Duplex At Riverview Terrace, Chevron']

In [8]:
locations = soup.select("div.single-room-text > h4")

In [9]:
locationss = [location.text for location in locations]

In [10]:
locationss

['Banana Island Estate Banana Island Ikoyi Lagos',
 'Oniru Victoria Island Lagos',
 'Victoria Island Lagos',
 'Ikoyi Lagos',
 'Parkview Estate Ikoyi Lagos',
 'Banana Island Estate Banana Island Ikoyi Lagos',
 'Old Ikoyi Ikoyi Lagos',
 'Victoria Island Victoria Island Lagos',
 'Surulere Ojuelegba Surulere Lagos',
 'Surulere Ojuelegba Surulere Lagos',
 'Peninsular Gardens Estate Sangotedo Lagos',
 'Off Okeho Street Ire Akari Isolo Lagos',
 'Ilasan Lekki Lagos',
 'Agungi Lekki Lagos',
 'Chevron Toll Gate Chevron Lekki Lagos',
 'Oniru Victoria Island Lagos',
 'Agungi Lekki Lagos',
 'Lekki Phase 1 Lekki Lagos',
 'Old Ikoyi Old Ikoyi Ikoyi Lagos',
 'Lekki Phase 1 Lekki Lagos',
 'Osapa London Lekki Lagos',
 'Chevron Lekki Lagos']

In [11]:
links = soup.select("div.single-room-text > a")

In [12]:
base_url = "https://www.propertypro.ng"
links_ = [base_url + link["href"] for link in links]

In [13]:
links_

['https://www.propertypro.ng/property/4-bedroom-flat-apartment-for-rent-banana-island-estate-banana-island-ikoyi-lagos-8FVLS',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-oniru-victoria-island-lagos-5FXPL',
 'https://www.propertypro.ng/property/3-bedroom-flat-apartment-for-rent-victoria-island-lagos-0FYSX',
 'https://www.propertypro.ng/property/4-bedroom-flat-apartment-for-rent-ikoyi-lagos-8GCDF',
 'https://www.propertypro.ng/property/flat-apartment-for-rent-parkview-estate-ikoyi-lagos-4GCEK',
 'https://www.propertypro.ng/property/4-bedroom-flat-apartment-for-rent-banana-island-estate-banana-island-ikoyi-lagos-0GCQG',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-old-ikoyi-ikoyi-lagos-1GCQK',
 'https://www.propertypro.ng/property/3-bedroom-flat-apartment-for-rent-victoria-island-victoria-island-lagos-2GCTW',
 'https://www.propertypro.ng/property/3-bedroom-flat-apartment-for-rent-surulere-ojuelegba-surulere-lagos-6GANR',
 'https://www.propertypro.ng/property/3-bedroom-flat-apartment-for-rent-surulere-ojuelegba-surulere-lagos-7GANR',
 'https://www.propertypro.ng/property/4-bedroom-house-for-sale-peninsular-gardens-estate-sangotedo-lagos-8FZFY',
 'https://www.propertypro.ng/property/1-bedroom-flat-apartment-for-rent-off-okeho-street-ire-akari-isolo-lagos-0GBAG',
 'https://www.propertypro.ng/property/2-bedroom-flat-apartment-for-rent-ilasan-lekki-lagos-5GCUF',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-agungi-lekki-lagos-2GCTX',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-chevron-toll-gate-chevron-lekki-lagos-6GCTW',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-oniru-victoria-island-lagos-4GCTW',
 'https://www.propertypro.ng/property/5-bedroom-house-for-rent-agungi-lekki-lagos-5GCTV',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-lekki-phase-1-lekki-lagos-0GCTU',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-old-ikoyi-old-ikoyi-ikoyi-lagos-6GCTT',
 'https://www.propertypro.ng/property/3-bedroom-flat-apartment-for-rent-lekki-phase-1-lekki-lagos-5GCSQ',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-osapa-london-lekki-lagos-0GBHX',
 'https://www.propertypro.ng/property/4-bedroom-house-for-rent-chevron-lekki-lagos-0GCRR']

In [14]:
state = [loc.split()[-1] for loc in locationss]

In [15]:
area = [loc.split()[-2] for loc in locationss]

In [16]:
state

['Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos',
 'Lagos']

In [17]:
area

['Ikoyi',
 'Island',
 'Island',
 'Ikoyi',
 'Ikoyi',
 'Ikoyi',
 'Ikoyi',
 'Island',
 'Surulere',
 'Surulere',
 'Sangotedo',
 'Isolo',
 'Lekki',
 'Lekki',
 'Lekki',
 'Island',
 'Lekki',
 'Lekki',
 'Ikoyi',
 'Lekki',
 'Lekki',
 'Lekki']

In [18]:
price = soup.select("div.n50 > h3")

In [19]:
prices_ = [pric.text.split()[-1] for pric in price]

In [20]:
prices_

['12,000,000',
 '7,000,000/year',
 '7,000,000/year',
 '20,000,000',
 '10,000,000',
 '12,000,000',
 '14,000,000',
 '7,000,000',
 '2,000,000',
 '2,000,000',
 '65,000,000',
 '4,000,000',
 '2,500,000',
 '5,500,000',
 '4,000,000',
 '7,500,000',
 '10,000,000',
 '7,000,000',
 '13,000,000',
 '4,500,000',
 '6,000,000/year',
 '3,500,000']

In [21]:
features = soup.select("div.fur-areea > span")

In [22]:
bedrooms = [bed.text for bed in features if bed.text.split()[-1]=="beds"]

In [23]:
bedrooms

['4 beds',
 '4 beds',
 '3 beds',
 '4 beds',
 '0 beds',
 '4 beds',
 '4 beds',
 '3 beds',
 '3 beds',
 '3 beds',
 '4 beds',
 '1 beds',
 '2 beds',
 '4 beds',
 '4 beds',
 '4 beds',
 '5 beds',
 '4 beds',
 '4 beds',
 '3 beds',
 '4 beds',
 '4 beds']

In [24]:
bathrooms = [baths.text for baths in features if baths.text.split()[-1]=="baths"]

In [25]:
bathrooms

['4 baths',
 '4 baths',
 '3 baths',
 '4 baths',
 '0 baths',
 '4 baths',
 '4 baths',
 '3 baths',
 '2 baths',
 '2 baths',
 '4 baths',
 '1 baths',
 '2 baths',
 '5 baths',
 '5 baths',
 '5 baths',
 '6 baths',
 '5 baths',
 '3 baths',
 '3 baths',
 '4 baths',
 '4 baths']

In [26]:
Toilets = [Toilets.text for Toilets in features if Toilets.text.split()[-1]=="Toilets"]

In [27]:
Toilets

['5 Toilets',
 '5 Toilets',
 '4 Toilets',
 '5 Toilets',
 '0 Toilets',
 '5 Toilets',
 '5 Toilets',
 '4 Toilets',
 '2 Toilets',
 '2 Toilets',
 '5 Toilets',
 '1 Toilets',
 '2 Toilets',
 '5 Toilets',
 '5 Toilets',
 '5 Toilets',
 '6 Toilets',
 '5 Toilets',
 '4 Toilets',
 '3 Toilets',
 '5 Toilets',
 '5 Toilets']

In [33]:
phones = soup.select("div.phone-icon")

In [34]:
agent_number = [agent.text.strip() for agent in phones]

In [36]:
agent_number

['08124269637',
 '07048089360',
 '07048089360',
 '08124269637',
 '08124269637',
 '08124269637',
 '08124269637',
 '08124269637',
 '08034918616',
 '08034918616',
 '09093333337',
 '08034918616',
 '09067320607',
 '09035137760',
 '09035137760',
 '09035137760',
 '09035137760',
 '09035137760',
 '08124269637',
 '07030820139',
 '08082163583',
 '08177766550']

In [37]:
dates = soup.select("div.single-room-text > h5")

In [38]:
date_added = [date.text for date in dates]

In [39]:
added_on = [date.partition("Added")[2].strip() for date in date_added]

In [40]:
added_on

['23 Dec 2021',
 '17 Jan 2022',
 '26 Jan 2022',
 '20 Feb 2022',
 '21 Feb 2022',
 '23 Feb 2022',
 '23 Feb 2022',
 '24 Feb 2022',
 '08 Feb 2022',
 '08 Feb 2022',
 '30 Jan 2022',
 '11 Feb 2022',
 '24 Feb 2022',
 '24 Feb 2022',
 '24 Feb 2022',
 '24 Feb 2022',
 '24 Feb 2022',
 '24 Feb 2022',
 '24 Feb 2022',
 '24 Feb 2022',
 '14 Feb 2022',
 '24 Feb 2022']

In [41]:
updated_on = [date.partition("Updated")[2].partition(", Added")[0].strip() if "Update" in date else date.partition("Added")[2].strip()  for date in date_added]

In [46]:
updated_on

['10 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '10 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '12 Feb 2022',
 '11 Feb 2022',
 '11 Feb 2022',
 '11 Feb 2022',
 '11 Feb 2022']

In [42]:
property_list = pd.DataFrame({"apartment":description,
                              "location": locationss,
                              "area": area,
                              "state": state,
                              "links": links_,
                              "price": prices_,
                              "bathrooms": bathrooms,
                              "bedrooms": bedrooms,
                              "toilets": Toilets,
                              "agent_number": agent_number,
                              "added_on": added_on,
                              "updated_on": updated_on
                            
                             })

In [43]:
property_list.head()

,apartment,location,area,state,links,price,bathrooms,bedrooms,toilets,agent_number,added_on,updated_on
0,Recently Renovated City View 4 Bedroom Apartme...,Banana Island Estate Banana Island Ikoyi Lagos,Ikoyi,Lagos,https://www.propertypro.ng/property/4-bedroom-...,"12,000,000",4 baths,4 beds,5 Toilets,08124269637,23 Dec 2021,24 Feb 2022
1,Serviced 4 Bedroom Semi Detached Duplex With E...,Oniru Victoria Island Lagos,Island,Lagos,https://www.propertypro.ng/property/4-bedroom-...,"7,000,000/year",4 baths,4 beds,5 Toilets,07048089360,17 Jan 2022,25 Feb 2022
2,Luxury 12 Units Of 3 Bedroom Apartments In A G...,Victoria Island Lagos,Island,Lagos,https://www.propertypro.ng/property/3-bedroom-...,"7,000,000/year",3 baths,3 beds,4 Toilets,07048089360,26 Jan 2022,25 Feb 2022
3,Luxury 4 Bedroom Apartment +bq,Ikoyi Lagos,Ikoyi,Lagos,https://www.propertypro.ng/property/4-bedroom-...,"20,000,000",4 baths,4 beds,5 Toilets,08124269637,20 Feb 2022,25 Feb 2022
4,Furnished 3 Bedroom Apartment + Bq,Parkview Estate Ikoyi Lagos,Ikoyi,Lagos,https://www.propertypro.ng/property/flat-apart...,"10,000,000",0 baths,0 beds,0 Toilets,08124269637,21 Feb 2022,25 Feb 2022

## For more pages

In [47]:
def pages_to_scrape(min_page, max_page):
    pages = []
    url = "https://www.propertypro.ng/property-for-rent?page=" 
    for i in range(min_page, max_page+1):
            pages.append(url + str(i))
    return pages

In [48]:
#pages

In [49]:
def apart_listing(pages):

    Description = []
    Links = []
    Locations = []
    State = []
    Price = []
    Bedrooms = []
    Bathrooms = []
    Toilets = []
    Agent_number = []
    Added_on = []
    Updated_on = []
    Area = []

    for page in pages:
        try:
                 response = requests.get(page)
        except:
                break
        data_ = response.text
        soup = BeautifulSoup(data_, "html.parser")
        listings = soup.find_all(class_ = "listings-property-title2")
        for listing in listings:
            Description.append(listing.text)
        locations = soup.select("div.single-room-text > h4")
        Locations_ = [location.text for location in locations]
        for location in locations:
            Locations.append(location.text)
        links = soup.select("div.single-room-text > a")
        for link in links:
            Links.append("https://www.propertypro.ng" + link["href"])

        for loc in Locations_:
            State.append(loc.split()[-1])
        for loc in Locations_:
            Area.append(loc.split()[-2])

        price = soup.select("div.n50 > h3")
        for pric in price:
            Price.append(pric.text.split()[-1])
        features = soup.select("div.fur-areea > span")
        for bed in features:
            if bed.text.split()[-1]=="beds":
                Bedrooms.append(bed.text)
        for baths in features:
            if baths.text.split()[-1] == "baths":
                Bathrooms.append(baths.text)
        for toilets in features:
            if toilets.text.split()[-1] == "Toilets":
                Toilets.append(toilets.text)
        phones = soup.select("div.phone-icon")
        for agent in phones:
            Agent_number.append(agent.text.strip())
        dates = soup.select("div.single-room-text > h5")
        Date_added = [date.text for date in dates]
        for date in Date_added:
            Added_on.append(date.partition("Added")[2].strip())
        for date in Date_added:
            if "Update" in date:
                Updated_on.append(date.partition("Updated")[2].partition(", Added")[0].strip())
            else:
                Updated_on.append(date.partition("Added")[2].strip())
    df = pd.DataFrame({'Description':Description, 'Location': Locations, 'Links': Links, 'State': State, 
                      'Area':Area, 'Price': Price,
                      'Bedrooms': Bedrooms, 'Bathrooms': Bathrooms, 'Toilets': Toilets,
                      'Agent_number': Agent_number, 'Added_on': Added_on, 'Updated_on': Updated_on})
    df.to_csv("apartment_rent_"+str(len(pages))+".csv", index=False)
    return df

In [ ]:
#first 21 pages
pages = pages_to_scrape(0,200)

In [ ]:
#first 21 pages
apart_listing(pages)

In [30]:
#page 202 to 407th
pages_1 = pages_to_scrape(202,340)

In [31]:
apart_listing(pages_1)

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
0,Executive Mini Flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,"900,000",beds,baths,Toilets,08028761350,01 Feb 2022,24 Feb 2022
1,Office Space,Adeola Odeku Victoria Island Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Island,"16,000,000/year",0 beds,0 baths,0 Toilets,08057121358,30 Jul 2021,19 Feb 2022
2,2 Bedroom Flat,"Akuru, Elebu Oluyole Extension Akala Express I...",https://www.propertypro.ng/property/2-bedroom-...,Oyo,Ibadan,"600,000/year",2 beds,0 baths,0 Toilets,07037117785,24 Jan 2022,19 Feb 2022
3,2bedroom Flat,Alpha Beach Road Igbo Efon Lekki Lagos,https://www.propertypro.ng/property/2-bedroom-...,Lagos,Lekki,"1,300,000/year",2 beds,2 baths,3 Toilets,08168285322,14 Jan 2022,19 Feb 2022
4,Very 4 Bedroom Duplex,Alalubosa Ibadan Oyo,https://www.propertypro.ng/property/4-bedroom-...,Oyo,Ibadan,"1,500,000/year",4 beds,4 baths,4 Toilets,08147747114,23 Jan 2022,19 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
1821,Newly Built 2 Bedroom Flat,Omolayo Estate Akobo Ibadan Oyo,https://www.propertypro.ng/property/2-bedroom-...,Oyo,Ibadan,"700,000",2 beds,2 baths,3 Toilets,08114892643,26 Jan 2022,17 Feb 2022
1822,Newly Built 2bedroom,Ayo Alabi Road Oleira Ogba Ikeja Lagos Oke Ira...,https://www.propertypro.ng/property/2-bedroom-...,Lagos,Ogba,"1,200,000/year",2 beds,2 baths,2 Toilets,09013487322,02 Feb 2022,17 Feb 2022
1823,5 Bedroom Duplex,Omole Phase 1 Ojodu Lagos,https://www.propertypro.ng/property/5-bedroom-...,Lagos,Ojodu,"6,000,000",5 beds,5 baths,6 Toilets,0812102622207037229294,25 Jan 2022,17 Feb 2022
1824,Newly Built 2 Bedroom Flat,Ogba Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ogba,"1,500,000",0 beds,0 baths,0 Toilets,07039402751,19 May 2021,17 Feb 2022
1825,4 Bedroom Duplex,Ajao Estate Isolo Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Isolo,"2,500,000/year",4 beds,0 baths,0 Toilets,08020391799,30 Jan 2022,17 Feb 2022

In [50]:
df1 = pd.read_csv("apartment_rent_201.csv")

In [51]:
df2 = pd.read_csv("apartment_rent_139.csv")

In [52]:
df = pd.concat([df1,df2], ignore_index=True)

In [54]:
df.head()

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
0,Recently Renovated City View 4 Bedroom Apartme...,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,"12,000,000",4 beds,4 baths,5 Toilets,8124269637,23 Dec 2021,24 Feb 2022
1,Brand New Fully Furnished 3bedroom Apartment I...,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Lekki,"4,500,000",3 beds,3 baths,3 Toilets,7030820139,24 Feb 2022,24 Feb 2022
2,Tastefully Built 4 Bedroom Semi Detached Duplex;,Osapa London Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,"6,000,000/year",4 beds,4 baths,5 Toilets,8082163583,14 Feb 2022,24 Feb 2022
3,Elegant 4 Bedroom Terrace Duplex At Riverview ...,Chevron Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,"3,500,000",4 beds,4 baths,5 Toilets,8177766550,24 Feb 2022,24 Feb 2022
4,4 Bedroom Apartments + Bq+gym+tennis Court,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,"12,000,000",4 beds,4 baths,5 Toilets,8124269637,23 Feb 2022,24 Feb 2022

In [55]:
df.shape

(6248, 12)

In [56]:
df["Price"] = df["Price"].apply(lambda x: x.split("/")[0].replace(',', '') )

In [57]:
df.head()

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
0,Recently Renovated City View 4 Bedroom Apartme...,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4 beds,4 baths,5 Toilets,8124269637,23 Dec 2021,24 Feb 2022
1,Brand New Fully Furnished 3bedroom Apartment I...,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Lekki,4500000,3 beds,3 baths,3 Toilets,7030820139,24 Feb 2022,24 Feb 2022
2,Tastefully Built 4 Bedroom Semi Detached Duplex;,Osapa London Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,6000000,4 beds,4 baths,5 Toilets,8082163583,14 Feb 2022,24 Feb 2022
3,Elegant 4 Bedroom Terrace Duplex At Riverview ...,Chevron Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,3500000,4 beds,4 baths,5 Toilets,8177766550,24 Feb 2022,24 Feb 2022
4,4 Bedroom Apartments + Bq+gym+tennis Court,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4 beds,4 baths,5 Toilets,8124269637,23 Feb 2022,24 Feb 2022

In [58]:
df["Price"].unique()

array(['12000000', '4500000', '6000000', '3500000', '14000000', '5000000',
       '2000000', '14000', '800000', '280000000', '35000000', '65000',
       '1200000', '7000000', '10000000', '900000', '9000000', '25000',
       '7500000', '2500000', '8500000', '300000', '600000', '16100000',
       '22000000', '14500000', '5500000', '1500000', '15000000', '550000',
       '1600000', '20000000', '2400000000', '30000', '18000000',
       '4000000', '400000', '9500000', '80000', '650000', '12500000',
       '520000', '700000', '50000', '11000000', '13500000', '19000000',
       '1000000000', '16500000', '1300000', '1000000', '8000000', '20000',
       '25000000', '1800000', '120000000', '1700000', '6500000', '45000',
       '500000', '3000000', '2800000', '350000', '300000000', '100000',
       '850000', '100000000', '450000', '1100000', '16000000', '950000',
       '250000', '200000', '320000', '45000000', '180000', '95000',
       '80000000', '2700000', '3700000', '480000', '24000000', '40000000',
       '40000', '160000000', '3200000', '4800000', '70000', '23000000',
       '60000', '5700000', '13000000', '32000000', '17000000', '17500000',
       '750000', '135000000', '35000', '2400000', '10500000', '2100000',
       '75000', '2600000', '150000', '85000000', '2200000', '750',
       '7100000', '65000000', '360000', '2300000', '375000000',
       '30000000', '650', '49572000', '1400000', '19600000', '600',
       '99500', '70000000', '90000', '112000000', '3800000', '7300000',
       '130000', '120000', '48000000', '7600000', '2550000', '850000000',
       '400009', '175000', '110000', '200000000', '280000', '155000000',
       '1350000', '430000', '170000', '12100000', '1900000', '3300000',
       '15000', '900000000', '170000000', '140000000', '60000000',
       '12690000', '75000000', '55000000', '17800000', '3500000000',
       '21840000', '39088000', '22000', '10000', '95000000', '1500000000',
       '1600000000', '85000', '90000000', '270000', '18500000',
       '42000000', '1450000', '290000000', '4400000', '27000000', '700',
       '1250000000', '550', '28000000', '450000000', '420000', '135000',
       '2000', '720000', '4600000', '1200009', '3012000', '4100000',
       '4200000', '230000', '8100000', '1300009', '3100000', '4700000',
       '600000000', '4900000', '780000', '1160000', '8500000000',
       '3000000000', '2175000', '15500000', '3600000', '700000000',
       '1250000', '2670000', '210000', '1200000000', '370000', '220000',
       '330000', '2900000', '1500', '15400000', '9600000', '175000000',
       '190000', '50000000', '4520000', '17000', '0', '833', '2750000',
       '55000', '57500', '625000', '590000', '14000000000', '31000000',
       '1100000000', '12000', '220000000', '22800000', '460000',
       '1650000', '18000', '2020000', '1020000', '950000000', '33000000'],
      dtype=object)

A house for 0,833,700,1000

In [59]:
cheap_apartments = df[df.Price.str.len() <= 5 ]
cheap_apartments

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
8,"6,000sqm Bay Of Warehouse",Lakowe Ajah Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ajah,14000,0 beds,0 baths,0 Toilets,9022355254,10 May 2021,24 Feb 2022
15,Open Plan Office Spaces,Along Oba Akinjobi Way Ikeja Gra Ikeja Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ikeja,65000,beds,baths,Toilets,8054797512,20 Oct 2021,24 Feb 2022
23,"Warehouse Space Measuring 47,200 Sqm",Acme Road Ogba Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ogba,25000,beds,baths,Toilets,8054797512,12 Oct 2021,24 Feb 2022
56,A Wing Of 120 Square Meters Of Space For Rent,Offadeniyi Jones Adeniyi Jones Ikeja Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ikeja,30000,beds,baths,2 Toilets,8050606090,03 Feb 2022,24 Feb 2022
64,Open Plan Office Space,Along Oba Akinjobi Way Ikeja Gra Ikeja Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ikeja,65000,beds,baths,Toilets,8054797512,11 Oct 2021,24 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6168,2bedrooms Apartment,Governor Road Governors Road Ikotun Igando Lagos,https://www.propertypro.ng/property/2-bedroom-...,Lagos,Igando,60000,2 beds,3 baths,2 Toilets,08060795036,05 Feb 2022,17 Feb 2022
6170,Comfortable Private Master Bedroom Suite,"First Unity Estate, Co Operative Bus Stop, Bad...",https://www.propertypro.ng/property/1-bedroom-...,Lagos,Ajah,20000,1 beds,1 baths,1 Toilets,09093333337,11 Apr 2021,22 Feb 2022
6188,Office Space On 3rd Floor Measuring 370sqm,Ogudu Ori Oke Ogudu Orike Ogudu Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ogudu,18000,0 beds,0 baths,0 Toilets,08022292982,15 Feb 2022,17 Feb 2022
6217,The Office Space For Intellectuals,Ademola Adetokunbo Victoria Island Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Island,40000,beds,1 baths,3 Toilets,09060005262,02 Dec 2021,17 Feb 2022
6219,An Exquisite Brand New Open Plan Office Spaces.,Off Ologun Agbaje Adeola Odeku Victoria Island...,https://www.propertypro.ng/property/commercial...,Lagos,Island,75000,beds,baths,Toilets,08025244936,09 Jan 2022,17 Feb 2022

In [60]:
df.drop(cheap_apartments.index, inplace=True)

In [61]:
df.head()

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
0,Recently Renovated City View 4 Bedroom Apartme...,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4 beds,4 baths,5 Toilets,8124269637,23 Dec 2021,24 Feb 2022
1,Brand New Fully Furnished 3bedroom Apartment I...,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Lekki,4500000,3 beds,3 baths,3 Toilets,7030820139,24 Feb 2022,24 Feb 2022
2,Tastefully Built 4 Bedroom Semi Detached Duplex;,Osapa London Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,6000000,4 beds,4 baths,5 Toilets,8082163583,14 Feb 2022,24 Feb 2022
3,Elegant 4 Bedroom Terrace Duplex At Riverview ...,Chevron Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,3500000,4 beds,4 baths,5 Toilets,8177766550,24 Feb 2022,24 Feb 2022
4,4 Bedroom Apartments + Bq+gym+tennis Court,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4 beds,4 baths,5 Toilets,8124269637,23 Feb 2022,24 Feb 2022

In [62]:
df.shape

(6068, 12)

In [63]:
df["Bedrooms"].unique()

array(['4 beds', '3 beds', '0 beds', '2 beds', '5 beds', ' beds',
       '1 beds', '10 beds', '6 beds', '9 beds', '7 beds', '8 beds'],
      dtype=object)

In [64]:
df["Bedrooms"] = df["Bedrooms"].apply(lambda x: x.strip() )

In [65]:
df["Bedrooms"].unique()

array(['4 beds', '3 beds', '0 beds', '2 beds', '5 beds', 'beds', '1 beds',
       '10 beds', '6 beds', '9 beds', '7 beds', '8 beds'], dtype=object)

In [66]:
no_beds = (df["Bedrooms"].str.startswith('beds'))
no_beds

0       False
1       False
2       False
3       False
4       False
        ...
6243    False
6244    False
6245    False
6246    False
6247    False
Name: Bedrooms, Length: 6068, dtype: bool

In [67]:
df["Bedrooms"].value_counts()

3 beds     1352
0 beds     1192
4 beds     1028
2 beds      971
1 beds      729
beds        410
5 beds      302
6 beds       51
10 beds      15
7 beds       13
8 beds        3
9 beds        2
Name: Bedrooms, dtype: int64

In [68]:
df["Bedrooms"].unique()

array(['4 beds', '3 beds', '0 beds', '2 beds', '5 beds', 'beds', '1 beds',
       '10 beds', '6 beds', '9 beds', '7 beds', '8 beds'], dtype=object)

In [69]:
df.loc[no_beds, ['Bedrooms']] = "0"

In [70]:
df["Bedrooms"].value_counts()

3 beds     1352
0 beds     1192
4 beds     1028
2 beds      971
1 beds      729
0           410
5 beds      302
6 beds       51
10 beds      15
7 beds       13
8 beds        3
9 beds        2
Name: Bedrooms, dtype: int64

In [71]:
df.Bedrooms = df.Bedrooms.map(lambda x: x.split()[0]).astype(int)

In [72]:
df["Bedrooms"].value_counts()

0     1602
3     1352
4     1028
2      971
1      729
5      302
6       51
10      15
7       13
8        3
9        2
Name: Bedrooms, dtype: int64

In [73]:
df.Description = df.Description.str.lower()
df.head()

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
0,recently renovated city view 4 bedroom apartme...,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4,4 baths,5 Toilets,8124269637,23 Dec 2021,24 Feb 2022
1,brand new fully furnished 3bedroom apartment i...,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Lekki,4500000,3,3 baths,3 Toilets,7030820139,24 Feb 2022,24 Feb 2022
2,tastefully built 4 bedroom semi detached duplex;,Osapa London Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,6000000,4,4 baths,5 Toilets,8082163583,14 Feb 2022,24 Feb 2022
3,elegant 4 bedroom terrace duplex at riverview ...,Chevron Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,3500000,4,4 baths,5 Toilets,8177766550,24 Feb 2022,24 Feb 2022
4,4 bedroom apartments + bq+gym+tennis court,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4,4 baths,5 Toilets,8124269637,23 Feb 2022,24 Feb 2022

In [74]:
for i in range(1, 6):
    df.loc[df.Description.str.contains(str(i)), 'Bedrooms'] = i
df.loc[df.Description.str.contains('two'), 'Bedrooms'] = 2 # for those written in words
df.loc[df.Description.str.contains('three'), 'Bedrooms'] = 3 # for those written in words

df.loc[df.Description.str.contains('and parlour'), 'Bedrooms'] = 1 # for 'room and parlour' apartments
df.loc[df.Description.str.contains('self'), 'Bedrooms'] = 1 # for 'self contained' apartments
df.loc[df.Description.str.contains('mini'), 'Bedrooms'] = 1 # for mini flats

In [75]:
df["Bedrooms"].value_counts()

3     1600
1     1353
4     1193
2     1184
5      385
0      316
6       26
7        7
8        2
10       1
9        1
Name: Bedrooms, dtype: int64

And I've reduced 1571 unknown rooms to 311!

In [76]:
zero_beds = df.loc[df["Bedrooms"]==0]
zero_beds

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
11,a storey commercial building for long lease,Adeniyi Jones Ikeja Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ikeja,35000000,0,baths,8 Toilets,8050606090,03 Dec 2021,24 Feb 2022
39,studio apartment,Parkview Estate Ikoyi Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ikoyi,1500000,0,0 baths,1 Toilets,8050606090,29 Nov 2021,24 Feb 2022
94,fully serviced & furnished office space,Idejo Adeola Odeku Victoria Island Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Island,11000000,0,baths,1 Toilets,8050606090,22 Nov 2021,24 Feb 2022
123,facing lekki epe expressway shop,Beside Golden Park Estate Abraham Adesanya Est...,https://www.propertypro.ng/property/commercial...,Lagos,Ajah,2500000,0,baths,Toilets,8160412420,28 Jan 2022,22 Feb 2022
156,newly built shop and office space,Utako District Utako Abuja,https://www.propertypro.ng/property/commercial...,Abuja,Utako,1700000,0,1 baths,1 Toilets,8111113467,11 May 2021,22 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6195,office space/show room,Street Garki 1 Abuja,https://www.propertypro.ng/property/commercial...,Abuja,1,2000000,0,0 baths,0 Toilets,08055070928,21 Jan 2022,17 Feb 2022
6207,warehouse,Ile Ise Awo Abeokuta Ogun,https://www.propertypro.ng/property/commercial...,Ogun,Abeokuta,2000000,0,0 baths,0 Toilets,07052090371,19 Aug 2021,17 Feb 2022
6221,a newly built a storey building commercial pro...,Ayobo Ipaja Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ipaja,2000000,0,0 baths,0 Toilets,07011526537,10 Feb 2022,17 Feb 2022
6232,spacious ground floor shop space,"Fola Oshibo Road, Lekki Phase 1 Lekki Lagos",https://www.propertypro.ng/property/commercial...,Lagos,Lekki,6000000,0,0 baths,0 Toilets,08033842143,25 Jan 2022,17 Feb 2022
6236,kings gate estate via la campaigne tropicana,Lacampaigne Tropicana Ibeju Lekki Lagos,https://www.propertypro.ng/property/land-for-s...,Lagos,Lekki,2100000,0,baths,Toilets,09154621665,14 Apr 2021,24 Feb 2022

In [77]:
df.drop(zero_beds.index, inplace=True)
df["Bedrooms"].unique()

array([ 4,  3,  1,  2,  5,  6, 10,  8,  7,  9])

Bathrooms

In [78]:
df["Bathrooms"].unique()

array(['4 baths', '3 baths', '0 baths', '2 baths', '5 baths', '1 baths',
       ' baths', '7 baths', '10 baths', '6 baths', '8 baths', '9 baths'],
      dtype=object)

In [79]:
df["Bathrooms"] = df["Bathrooms"].str.strip() # cleaning the starting and trailing whitespaces

df["Bathrooms"].unique()

array(['4 baths', '3 baths', '0 baths', '2 baths', '5 baths', '1 baths',
       'baths', '7 baths', '10 baths', '6 baths', '8 baths', '9 baths'],
      dtype=object)

Toilets

In [80]:
df["Toilets"].unique()

array(['5 Toilets', '3 Toilets', '0 Toilets', '2 Toilets', '6 Toilets',
       '1 Toilets', '4 Toilets', ' Toilets', '8 Toilets', '10 Toilets',
       '7 Toilets', '9 Toilets'], dtype=object)

In [81]:
df["Toilets"] = df["Toilets"].str.strip() # cleaning the starting and trailing whitespaces

df["Toilets"].unique()

array(['5 Toilets', '3 Toilets', '0 Toilets', '2 Toilets', '6 Toilets',
       '1 Toilets', '4 Toilets', 'Toilets', '8 Toilets', '10 Toilets',
       '7 Toilets', '9 Toilets'], dtype=object)

In [82]:
no_baths = df[df.Bathrooms.str.startswith('baths')]
no_baths

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
44,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,baths,Toilets,8028761350,01 Feb 2022,24 Feb 2022
66,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,baths,Toilets,8028761350,01 Feb 2022,24 Feb 2022
74,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,baths,Toilets,8028761350,01 Feb 2022,24 Feb 2022
163,very clean and decent mini flat,Shomolu Shomolu Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Shomolu,500000,1,baths,Toilets,9061623299,30 Nov 2021,22 Feb 2022
168,5 bedroom semi detached duplex,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/5-bedroom-...,Lagos,Lekki,10000000,5,baths,Toilets,7085348881,14 Feb 2022,22 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6167,a 400sqm open plan office space,Awolowo Way Ikeja Lagos,https://www.propertypro.ng/property/commercial...,Lagos,Ikeja,10000000,4,baths,4 Toilets,08111349600,15 Feb 2022,17 Feb 2022
6186,2 bedroom flat,Iletuntun Jericho Gra Extension Jericho Ibadan...,https://www.propertypro.ng/property/house-for-...,Oyo,Ibadan,350000,2,baths,Toilets,07030737894,25 Sep 2021,17 Feb 2022
6218,commercial complex of 90 shops/offices on 3 fl...,Aminu Kano Wuse2 Wuse 2 Abuja,https://www.propertypro.ng/property/commercial...,Abuja,2,950000000,3,baths,Toilets,08030986639,02 Aug 2021,17 Feb 2022
6224,an executive mini flat,Isheri Egbeda Alimosho Lagos,https://www.propertypro.ng/property/1-bedroom-...,Lagos,Alimosho,500000,1,baths,2 Toilets,08060882613,12 Feb 2022,17 Feb 2022
6238,fully furnished four bedroom loft/pent house w...,Off Banana Island Road(not Inside Banana Islan...,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,18000000,4,baths,Toilets,09023459596,25 Jan 2022,17 Feb 2022

In [83]:
df[df["Toilets"].str.startswith('T')]

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
44,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,baths,Toilets,8028761350,01 Feb 2022,24 Feb 2022
66,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,baths,Toilets,8028761350,01 Feb 2022,24 Feb 2022
74,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,baths,Toilets,8028761350,01 Feb 2022,24 Feb 2022
163,very clean and decent mini flat,Shomolu Shomolu Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Shomolu,500000,1,baths,Toilets,9061623299,30 Nov 2021,22 Feb 2022
168,5 bedroom semi detached duplex,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/5-bedroom-...,Lagos,Lekki,10000000,5,baths,Toilets,7085348881,14 Feb 2022,22 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6148,4 bedroom fully detached duplex,Ikate Lekki Lagos,https://www.propertypro.ng/property/house-for-...,Lagos,Lekki,170000000,4,baths,Toilets,08030996281,10 Feb 2022,24 Feb 2022
6159,fully serviced 3bedroom terrace house,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/house-for-...,Lagos,Lekki,4500000,3,baths,Toilets,08138837188,25 Jan 2022,17 Feb 2022
6186,2 bedroom flat,Iletuntun Jericho Gra Extension Jericho Ibadan...,https://www.propertypro.ng/property/house-for-...,Oyo,Ibadan,350000,2,baths,Toilets,07030737894,25 Sep 2021,17 Feb 2022
6218,commercial complex of 90 shops/offices on 3 fl...,Aminu Kano Wuse2 Wuse 2 Abuja,https://www.propertypro.ng/property/commercial...,Abuja,2,950000000,3,baths,Toilets,08030986639,02 Aug 2021,17 Feb 2022
6238,fully furnished four bedroom loft/pent house w...,Off Banana Island Road(not Inside Banana Islan...,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,18000000,4,baths,Toilets,09023459596,25 Jan 2022,17 Feb 2022

I could fill replace the baths without a digit value with their corresponding toilet values, provided that their toilet has a digit value.

In [84]:
df.loc[df["Bathrooms"].str.startswith('baths'), 'Bathrooms'] = df["Toilets"].map(lambda x: x.split(' ')[0])

In [85]:
df["Bathrooms"].unique()

array(['4 baths', '3 baths', '0 baths', '2 baths', '5 baths', '1 baths',
       'Toilets', '7 baths', '10 baths', '6 baths', '8 baths', '7',
       '9 baths', '3', '2', '4', '6'], dtype=object)

In [86]:
no_num_Bathrooms = df[df.Bathrooms.str.startswith('Toilets')]
no_num_Bathrooms

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
44,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,Toilets,Toilets,8028761350,01 Feb 2022,24 Feb 2022
66,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,Toilets,Toilets,8028761350,01 Feb 2022,24 Feb 2022
74,executive mini flat,Seaside Estate Badore Ajah Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ajah,900000,1,Toilets,Toilets,8028761350,01 Feb 2022,24 Feb 2022
163,very clean and decent mini flat,Shomolu Shomolu Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Shomolu,500000,1,Toilets,Toilets,9061623299,30 Nov 2021,22 Feb 2022
168,5 bedroom semi detached duplex,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/5-bedroom-...,Lagos,Lekki,10000000,5,Toilets,Toilets,7085348881,14 Feb 2022,22 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6148,4 bedroom fully detached duplex,Ikate Lekki Lagos,https://www.propertypro.ng/property/house-for-...,Lagos,Lekki,170000000,4,Toilets,Toilets,08030996281,10 Feb 2022,24 Feb 2022
6159,fully serviced 3bedroom terrace house,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/house-for-...,Lagos,Lekki,4500000,3,Toilets,Toilets,08138837188,25 Jan 2022,17 Feb 2022
6186,2 bedroom flat,Iletuntun Jericho Gra Extension Jericho Ibadan...,https://www.propertypro.ng/property/house-for-...,Oyo,Ibadan,350000,2,Toilets,Toilets,07030737894,25 Sep 2021,17 Feb 2022
6218,commercial complex of 90 shops/offices on 3 fl...,Aminu Kano Wuse2 Wuse 2 Abuja,https://www.propertypro.ng/property/commercial...,Abuja,2,950000000,3,Toilets,Toilets,08030986639,02 Aug 2021,17 Feb 2022
6238,fully furnished four bedroom loft/pent house w...,Off Banana Island Road(not Inside Banana Islan...,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,18000000,4,Toilets,Toilets,09023459596,25 Jan 2022,17 Feb 2022

In [87]:
df.drop(df.loc[df["Bathrooms"]=="Toilets"].index, inplace=True)

In [88]:
df["Bathrooms"].unique()

array(['4 baths', '3 baths', '0 baths', '2 baths', '5 baths', '1 baths',
       '7 baths', '10 baths', '6 baths', '8 baths', '7', '9 baths', '3',
       '2', '4', '6'], dtype=object)

In [89]:
df["Bathrooms"] = df["Bathrooms"].apply(lambda x: x.split(' ')[0]).astype(int) # converting Bathrooms to integers

df["Bathrooms"].unique()

array([ 4,  3,  0,  2,  5,  1,  7, 10,  6,  8,  9])

In [90]:
df[df["Bathrooms"] == 0]

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
7,newly built 3 bedroom flats,Sangotedo Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Sangotedo,2000000,3,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
16,2 bedrooms flat,Iwaya Yaba Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Yaba,1200000,2,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
20,newly built 3 bedroom apartment,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Lekki,5000000,3,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
26,premium 3 bedroom apartment +pool+gym+elevator...,Parkview Estate Parkview Estate Ikoyi Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ikoyi,7500000,3,0,0 Toilets,8124269637,02 Feb 2022,24 Feb 2022
28,brand new 2bedrooms flat apartment,Orchid Road Lekki Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Lekki,2500000,2,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6227,self contain apartment,"In A Secure Estate, Ologolo Lekki Lagos",https://www.propertypro.ng/property/1-bedroom-...,Lagos,Lekki,900000,1,0,1 Toilets,08094333251,02 Feb 2022,17 Feb 2022
6228,6 units of 3/4 bedroom of blocks of flats,Oniru Victoria Island Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Island,33000000,4,0,0 Toilets,08145449601,19 Jan 2022,17 Feb 2022
6233,"2 units of 5 bedroom duplex, 2 bedroom guest c...",Maitama Abuja,https://www.propertypro.ng/property/house-for-...,Abuja,Maitama,50000000,5,0,0 Toilets,08131317621,02 Feb 2022,17 Feb 2022
6246,newly built 2 bedroom flat,Ogba Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ogba,1500000,2,0,0 Toilets,07039402751,19 May 2021,17 Feb 2022
6247,4 bedroom duplex,Ajao Estate Isolo Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Isolo,2500000,4,0,0 Toilets,08020391799,30 Jan 2022,17 Feb 2022

In [91]:
df.loc[df["Bathrooms"] == 0, 'Bathrooms'] = df["Toilets"].map(lambda x: x.split(' ')[0] if len(x.split(' '))  > 1 else 0).astype(int)
df[df["Bathrooms"] == 0]

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
7,newly built 3 bedroom flats,Sangotedo Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Sangotedo,2000000,3,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
16,2 bedrooms flat,Iwaya Yaba Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Yaba,1200000,2,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
20,newly built 3 bedroom apartment,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Lekki,5000000,3,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
26,premium 3 bedroom apartment +pool+gym+elevator...,Parkview Estate Parkview Estate Ikoyi Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ikoyi,7500000,3,0,0 Toilets,8124269637,02 Feb 2022,24 Feb 2022
28,brand new 2bedrooms flat apartment,Orchid Road Lekki Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Lekki,2500000,2,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6201,5 bedroom semi detached duplex,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/house-for-...,Lagos,Lekki,6000000,5,0,0 Toilets,08138837188,25 Jan 2022,17 Feb 2022
6228,6 units of 3/4 bedroom of blocks of flats,Oniru Victoria Island Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Island,33000000,4,0,0 Toilets,08145449601,19 Jan 2022,17 Feb 2022
6233,"2 units of 5 bedroom duplex, 2 bedroom guest c...",Maitama Abuja,https://www.propertypro.ng/property/house-for-...,Abuja,Maitama,50000000,5,0,0 Toilets,08131317621,02 Feb 2022,17 Feb 2022
6246,newly built 2 bedroom flat,Ogba Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ogba,1500000,2,0,0 Toilets,07039402751,19 May 2021,17 Feb 2022
6247,4 bedroom duplex,Ajao Estate Isolo Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Isolo,2500000,4,0,0 Toilets,08020391799,30 Jan 2022,17 Feb 2022

If the bedroom is just 1, then the bathroom has to be one too.

In [92]:
df.loc[df["Bathrooms"] == 0, 'Bathrooms'] = df["Bedrooms"].apply(lambda x: x if x == 1 else 0)

df[df["Bathrooms"] == 0]

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
7,newly built 3 bedroom flats,Sangotedo Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Sangotedo,2000000,3,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
16,2 bedrooms flat,Iwaya Yaba Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Yaba,1200000,2,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
20,newly built 3 bedroom apartment,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Lekki,5000000,3,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
26,premium 3 bedroom apartment +pool+gym+elevator...,Parkview Estate Parkview Estate Ikoyi Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ikoyi,7500000,3,0,0 Toilets,8124269637,02 Feb 2022,24 Feb 2022
28,brand new 2bedrooms flat apartment,Orchid Road Lekki Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Lekki,2500000,2,0,0 Toilets,8028761350,31 Jan 2022,24 Feb 2022
...,...,...,...,...,...,...,...,...,...,...,...,...
6201,5 bedroom semi detached duplex,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/house-for-...,Lagos,Lekki,6000000,5,0,0 Toilets,08138837188,25 Jan 2022,17 Feb 2022
6228,6 units of 3/4 bedroom of blocks of flats,Oniru Victoria Island Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Island,33000000,4,0,0 Toilets,08145449601,19 Jan 2022,17 Feb 2022
6233,"2 units of 5 bedroom duplex, 2 bedroom guest c...",Maitama Abuja,https://www.propertypro.ng/property/house-for-...,Abuja,Maitama,50000000,5,0,0 Toilets,08131317621,02 Feb 2022,17 Feb 2022
6246,newly built 2 bedroom flat,Ogba Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Ogba,1500000,2,0,0 Toilets,07039402751,19 May 2021,17 Feb 2022
6247,4 bedroom duplex,Ajao Estate Isolo Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Isolo,2500000,4,0,0 Toilets,08020391799,30 Jan 2022,17 Feb 2022

I'd just fill them in with the number of bedrooms (this should be accurate in most cases except in the instances where there's an additional bathroom for the sitting room)

In [93]:
df.loc[df["Bathrooms"] == 0, 'Bathrooms'] = df["Bedrooms"]

df["Bedrooms"].value_counts()

3     1549
1     1182
4     1153
2     1144
5      359
6       26
7        5
8        2
10       1
9        1
Name: Bedrooms, dtype: int64

In [94]:
df["Toilets"].unique()

array(['5 Toilets', '3 Toilets', '0 Toilets', '2 Toilets', '6 Toilets',
       '1 Toilets', '4 Toilets', '8 Toilets', '10 Toilets', '7 Toilets',
       'Toilets', '9 Toilets'], dtype=object)

In [95]:
df["Toilets"].value_counts()

0 Toilets     1264
4 Toilets     1116
5 Toilets      898
3 Toilets      885
1 Toilets      484
2 Toilets      429
6 Toilets      260
7 Toilets       48
10 Toilets      13
8 Toilets       11
Toilets         10
9 Toilets        4
Name: Toilets, dtype: int64

In [96]:
df.drop(df.loc[df["Toilets"]=="Toilets"].index, inplace=True)

In [97]:
df["Toilets"].value_counts()

0 Toilets     1264
4 Toilets     1116
5 Toilets      898
3 Toilets      885
1 Toilets      484
2 Toilets      429
6 Toilets      260
7 Toilets       48
10 Toilets      13
8 Toilets       11
9 Toilets        4
Name: Toilets, dtype: int64

In [98]:
df["Toilets"] = df["Toilets"].apply(lambda x: x.split(' ')[0]).astype(int) # converting Toilets to integers

df["Toilets"].unique()

array([ 5,  3,  0,  2,  6,  1,  4,  8, 10,  7,  9])

In [99]:
df.sample(10)

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Toilets,Agent_number,Added_on,Updated_on
1,brand new fully furnished 3bedroom apartment i...,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Lekki,4500000,3,3,3,7030820139,24 Feb 2022,24 Feb 2022
5760,executive 4 bedroom semi detached duplex,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,6000000,4,4,5,08037939912,21 Dec 2021,19 Feb 2022
4081,fully serviced and furnished 2bedroom flat,By Eletu Way Osapa London Lekki Lagos,https://www.propertypro.ng/property/house-for-...,Lagos,Lekki,3000000,2,2,0,8133194443,30 Nov 2021,19 Feb 2022
5747,executive 3 bedroom flat,Omole Ph2 Via Ikeja Ikeja Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Ikeja,2500000,3,4,4,09068622049,01 Feb 2022,19 Feb 2022
2506,a brand new 4 bedroom semi detached duplex wit...,Osapa London Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,6000000,4,4,5,7032060222,08 Feb 2022,22 Feb 2022
4842,brand new 2 bedroom flat,Ishaga Road Iju Lagos,https://www.propertypro.ng/property/flat-apart...,Lagos,Iju,1200000,2,2,0,08033149535,10 May 2021,19 Feb 2022
277,newly renovated 2bedroom flat,Off Coker Road. Ilupeju Industrial Estate Ilup...,https://www.propertypro.ng/property/2-bedroom-...,Lagos,Ilupeju,1500000,2,1,1,8086267650,24 Feb 2022,24 Feb 2022
3748,wonderful and nice mini flat,Ifako Ogba Ogba Lagos,https://www.propertypro.ng/property/1-bedroom-...,Lagos,Ogba,400000,1,1,0,8100073388,30 Jan 2022,21 Feb 2022
517,furnished 3 bedroom apartment with amazing fac...,Oniru Victoria Island Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Island,6000000,3,3,4,7048089360,18 Jan 2022,24 Feb 2022
1255,4 bedroom semi detached house with 2 rooms bq ...,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,8000000,4,4,4,9053835258,03 Feb 2022,23 Feb 2022

Let's drop toilet column because some new houses build toilet and bathroom together

In [100]:
df.drop('Toilets', axis=1, inplace=True)

In [101]:
df.head()

,Description,Location,Links,State,Area,Price,Bedrooms,Bathrooms,Agent_number,Added_on,Updated_on
0,recently renovated city view 4 bedroom apartme...,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4,4,8124269637,23 Dec 2021,24 Feb 2022
1,brand new fully furnished 3bedroom apartment i...,Lekki Phase 1 Lekki Lagos,https://www.propertypro.ng/property/3-bedroom-...,Lagos,Lekki,4500000,3,3,7030820139,24 Feb 2022,24 Feb 2022
2,tastefully built 4 bedroom semi detached duplex;,Osapa London Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,6000000,4,4,8082163583,14 Feb 2022,24 Feb 2022
3,elegant 4 bedroom terrace duplex at riverview ...,Chevron Lekki Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Lekki,3500000,4,4,8177766550,24 Feb 2022,24 Feb 2022
4,4 bedroom apartments + bq+gym+tennis court,Banana Island Estate Banana Island Ikoyi Lagos,https://www.propertypro.ng/property/4-bedroom-...,Lagos,Ikoyi,12000000,4,4,8124269637,23 Feb 2022,24 Feb 2022

In [102]:
df.to_csv('house_data_wragled.csv', index=False)